- hosts: all

  tasks:
    - name: Transfer the weedfs script
      copy: src=runfsserver.sh dest=/tmp/ mode=0777

    - name: Create file for filer server logs
      ansible.builtin.file:
        path: /tmp/fsfilerrun.logs
        state: touch

    - name: Install seaweedfs and start filer server
      ansible.builtin.shell: nohup /tmp/runfsserver.sh {{index . 0}} {{index . 1}} </dev/null >/tmp/fsfilerrun.logs 2>&1 &
      become: true